# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AdaptiveLayoutWithNSLayoutHelper' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for AdaptiveLayoutWithNSLayoutHelper
  pod 'Masonry'

  target 'AdaptiveLayoutWithNSLayoutHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AdaptiveLayoutWithNSLayoutHelperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
