# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StripeTextField' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StripeTextField
  pod 'Stripe'
  
  target 'StripeTextFieldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StripeTextFieldUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
