# Uncomment the next line to define a global platform for your project
platform :ios, '9.1'

target 'CaknowGZ' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CaknowGZ

#    pod 'SDWebImage'
#    pod 'AFNetworking'
#    pod 'SVProgressHUD'
    pod 'Google/SignIn'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
#    pod 'Stripe'
#    pod 'Cloudinary'
#    pod 'CardIO'
#    pod 'Fabric'
#    pod 'TwitterKit'
#    pod 'TwitterCore'
    pod 'Masonry'
    
    
  target 'CaknowGZTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CaknowGZUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


