# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KSDeferredTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KSDeferredTest
  pod 'KSDeferred', git: 'https://github.com/RetVal/deferred.git', :tag => '0.3.4.2'
  target 'KSDeferredTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KSDeferredTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
